### ISSUE TITLE
errore html su slide 81 di html in TPSI 3

### ISSUE THREAD

**Issue by Gervasio-Gregorio** [ittagnelli/3INFO_2425#200]
sulla slide https://tpsi.mancusoa.it/3/html/#/81 l'html da un risultato diverso rispetto  a quello a fianco (<caption>A AND B</caption>) con risultato A OR B sull lato

**Comment by profmancusoa** [comment]
ok 100 punti

**Comment by profmancusoa** [comment]
la prossima volta apri issue nel repo corretto
